import { Project } from "./project.interface";

export const PROJECTS: Project[] = [
    {
        "title": "Fraud Detect ML",
        "image": "assets/images/fraud/fraud.jpg",
        "gallery": ["assets/images/fraud/fraud.jpg"],
        "galleryTitle": ["Fraud Detect ML"],
        "technologies": ["Python", "Pandas", "Sklearn"],
        "galeryId": "FraudDetect",
        "github": "https://github.com/JonnHenry/FraudDetectML",
        "description": "FraudDetectML is a machine learning project that detects fraud in bank account openings using synthetic data generated by a CTGAN trained on anonymized real-world data.",
        "idLink": "fraud_id",
        "idImage": "fraud_image",
        "descriptionIsShow": false
    },
    {
        "title": "30DayChartChallenge",
        "image": "assets/images/30_challengue/ImageLanding.png",
        "gallery": ["assets/images/30_challengue/ImageLanding.png"],
        "galleryTitle": ["30DayChartChallenge"],
        "galeryId": "Challengue",
        "technologies": ["Quarto", "R", "Datawrapper", "Power BI"],
        "description": "#30DayChartChallenge is an annual data visualization challenge where participants create and share a chart every day for 30 days, usually during April. Each day has a specific theme or prompt, encouraging creativity and skill development in data visualization.",
        "github": "https://github.com/JonnHenry/30DayChartChallenge",
        "idLink": "challengue_id",
        "idImage": "challengue_image",
        "descriptionIsShow": false
      },
      {
        "title": "DengAI",
        "image": "assets/images/dengueai/dengue.jpg",
        "gallery": ["assets/images/dengueai/dengue.jpg"],
        "galleryTitle": ["DengAI"],
        "technologies": ["Python", "Pandas", "Sklearn"],
        "galeryId": "DengAI",
        "description": "This repository applies the KDD (Knowledge Discovery in Databases) methodology to develop a machine learning model",
        "github": "https://github.com/JonnHenry/DengAI_predicting_disease_spread_machine_learning",
        "idLink": "dengue_id",
        "idImage": "dengue_image",
        "descriptionIsShow": false
      },
      {
        "title": "Big Data",
        "image": "assets/images/big_data/project.jpg",
        "gallery": ["assets/images/big_data/project.jpg"],
        "galleryTitle": ["Big Data Project Managment"],
        "technologies": ["Python", "Pandas", "MLflow", "DVC", "Sklearn"],
        "galeryId": "Data",
        "description": "Organized project structure for creating a machine learning model, including configuration files, staged data (raw, processed, final), experimental notebooks, documentation, and usage examples",
        "github": "https://github.com/JonnHenry/13MBID_gestion_proyectos",
        "idLink": "big_id",
        "idImage": "big_image",
        "descriptionIsShow": false
      },
      {
        "title": "Sentiment Analysis",
        "image": "assets/images/sentimentAnalysis/andrezlasso.jpg",
        "galleryTitle": ["Sentiment Analysis"],
        "gallery": ["assets/images/sentimentAnalysis/andrezlasso.jpg"],
        "technologies": ["Python", "Jupyter"],
        "galeryId": "Sentiment",
        "github": "https://github.com/TheWorstOne/SentimentAnalysisEcuador2021",
        "externalLink": "https://github.com/TheWorstOne/SentimentAnalysisEcuador2021#----sentimentanalysisecuador2021",
        "description": "Sentiment Analysis application for the presidential elections Ecuador 2021 using Twitter API, as well as to train a model for classifying the sentiments of these tweets.",
        "idLink": "sentiment_id",
        "idImage": "sentiment_image",
        "descriptionIsShow": false
      },
      {
        "title": "KDD Data Mining",
        "image": "assets/images/kdd/aids.jpg",
        "gallery": ["assets/images/kdd/aids.jpg"],
        "galleryTitle": ["AIDS KDD"],
        "technologies": ["Python", "Pandas", "Sklearn"],
        "galeryId": "KDD",
        "description": "This repository applies the KDD (Knowledge Discovery in Databases) methodology to develop a machine learning model",
        "github": "https://github.com/JonnHenry/KDD_data_mining/tree/master",
        "idLink": "kdd_id",
        "idImage": "kdd_image",
        "descriptionIsShow": false
      },
      {
        "title": "Dashboard Sparkend",
        "image": "assets/images/sparkEnd/flightreport.png",
        "gallery": ["assets/images/sparkEnd/flightreport.png"],
        "galleryTitle": ["Dashboard"],
        "technologies": ["Hadoop", "Spark", "Pyspark", "Flask", "Angular"],
        "galeryId": "Sparkend",
        "github": "https://github.com/TheWorstOne/Sparkend",
        "externalLink": "https://sparkers-7bb48.web.app/devs",
        "description": "An application that queries about the data of historical flights of United States airlines. This project was designed to work as a front-end on a lambda architecture implemented with Hadoop-Spark on the backend.",
        "idLink": "dashboard_id",
        "idImage": "dashboard_image",
        "descriptionIsShow": false
      },
      {
        "title": "Text Clustering",
        "image": "assets/images/textClustering/text-clustering.jpg",
        "galleryTitle": ["Text Clustering"],
        "gallery": ["assets/images/textClustering/text-clustering.jpg"],
        "technologies": ["Python", "Pandas"],
        "galeryId": "Clustering",
        "github": "https://github.com/JonnHenry/TextClustering",
        "externalLink": "https://github.com/JonnHenry/TextClustering/blob/master/Clusters_TextMining.ipynb",
        "description": "Project applying the knowledge acquired from Text Mining",
        "idLink": "clustering_id",
        "idImage": "clustering_image",
        "descriptionIsShow": false
      },
      {
        "title": "Example DAGs",
        "image": "assets/images/airflow/AirflowLogo.png",
        "gallery": ["assets/images/30_challengue/ImageLanding.png"],
        "galleryTitle": ["Airflow"],
        "galeryId": "DAGs",
        "technologies": ["Python", "Airflow", "S3"],
        "description": "Example of use Airflow to create Data-Scheduling",
        "github": "https://github.com/JonnHenry/Data-Scheduling",
        "idLink": "dag_id",
        "idImage": "dag_image",
        "descriptionIsShow": false
      },
      {
        "title": "Booth's Algorithm",
        "image": "assets/images/bothAlgorithm/interfaz_1.jpg",
        "gallery": [
          "assets/images/bothAlgorithm/interfaz_1.jpg",
          "assets/images/bothAlgorithm/interfaz_2.jpg"
        ],
        "galeryId": "Both",
        "technologies": ["Java"],
        "galleryTitle": ["Empty", "Results"],
        "github": "https://github.com/JonnHenry/BoothAlgorithm",
        "description": "This project was created to implement Booth's algorithm using the Java language to fully understand how the algorithm works.",
        "idLink": "both_id",
        "idImage": "both_image",
        "descriptionIsShow": false
      },
      {
        "title": "Qr Runner",
        "technologies": ["Android Studio", "Angular", "Ionic"],
        "gallery": [
          "assets/images/qrRunner/loginScreen.png",
          "assets/images/qrRunner/instructions.png",
          "assets/images/qrRunner/game.png",
          "assets/images/qrRunner/result.jpg"
        ],
        "galeryId": "QrRunner",
        "image": "assets/images/qrRunner/loginScreen.png",
        "galleryTitle": ["Login Screen","Instructions","Game Screen","Results"],
        "github": "https://github.com/JonnHenry/QrRunner",
        "description": "QrRunner is an application created as a game for the Student Week at the University of Cuenca. I made this game for the Microsoft community to which I belong.",
        "idLink": "runner_id",
        "idImage": "runner_image",
        "descriptionIsShow": false
      }
  ]